name: bug反馈
description: 出现了bug？在此反馈
title: "[BUG]"
labels: 'bug'
assignees: 'huoyan1231'
body:
- type: textarea
  id: desc
  attributes:
    label: 什么bug？
    description: "请描述你遇到的bug，如果可以的话请上传视频或截图(建议模糊网址部分)"
  validations:
    required: true
- type: checkboxes
  id: type
  attributes:
    label: 你在哪个项目中遇到了这个问题？
    description: 请选择你遇到项目的问题，如果一个问题在两个项目中同时存在，请全部勾选
    options:
      - label: SonglistEdt
      - label: UnlockEdt
  validations:
    required: true


